/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChambresRouteImport } from './routes/chambres'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as GolfRouteImport } from './routes/golf'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as RestaurantsRouteImport } from './routes/restaurants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChambresRoute = ChambresRouteImport.update({
  id: '/chambres',
  path: '/chambres',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const GolfRoute = GolfRouteImport.update({
  id: '/golf',
  path: '/golf',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chambres': typeof ChambresRoute
  '/evenements': typeof EvenementsRoute
  '/golf': typeof GolfRoute
  '/reservation': typeof ReservationRoute
  '/restaurants': typeof RestaurantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chambres': typeof ChambresRoute
  '/evenements': typeof EvenementsRoute
  '/golf': typeof GolfRoute
  '/reservation': typeof ReservationRoute
  '/restaurants': typeof RestaurantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chambres': typeof ChambresRoute
  '/evenements': typeof EvenementsRoute
  '/golf': typeof GolfRoute
  '/reservation': typeof ReservationRoute
  '/restaurants': typeof RestaurantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chambres'
    | '/evenements'
    | '/golf'
    | '/reservation'
    | '/restaurants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chambres'
    | '/evenements'
    | '/golf'
    | '/reservation'
    | '/restaurants'
  id:
    | '__root__'
    | '/'
    | '/chambres'
    | '/evenements'
    | '/golf'
    | '/reservation'
    | '/restaurants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChambresRoute: typeof ChambresRoute
  EvenementsRoute: typeof EvenementsRoute
  GolfRoute: typeof GolfRoute
  ReservationRoute: typeof ReservationRoute
  RestaurantsRoute: typeof RestaurantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chambres': {
      id: '/chambres'
      path: '/chambres'
      fullPath: '/chambres'
      preLoaderRoute: typeof ChambresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golf': {
      id: '/golf'
      path: '/golf'
      fullPath: '/golf'
      preLoaderRoute: typeof GolfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChambresRoute: ChambresRoute,
  EvenementsRoute: EvenementsRoute,
  GolfRoute: GolfRoute,
  ReservationRoute: ReservationRoute,
  RestaurantsRoute: RestaurantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
